repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts  
namespace: todo-app
releases:
  - name: auth-api
    chart: ./charts/auth-api  # Path to your chart directory
  - name: frontend
    chart: ./charts/frontend
  - name: users-api
    chart: ./charts/users-api
  - name: todos-api
    chart: ./charts/todos-api
  - name: log-message-procesor
    chart: ./charts/log-message-processor
  - name: redis
    chart: ./charts/redis
  - name: prometheus
    chart: prometheus-community/prometheus
  - name: grafana
    chart: grafana/grafana  

 
