apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-message-processor.fullname" . }}
  namespace: distribuidos
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "log-message-processor.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "log-message-processor.name" . }}
    spec:
      containers:
        - name: log-message-processor-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: REDIS_HOST
              value: "{{ .Values.env.REDIS_HOST }}"
            - name: REDIS_PORT
              value: "{{ .Values.env.REDIS_PORT }}"
            - name: REDIS_CHANNEL
              value: "{{ .Values.env.REDIS_CHANNEL }}"
