apiVersion: v1
kind: Service
metadata:
  name: {{ include "log-message-processor.fullname" . }}
  namespace: distribuidos
spec:
  selector:
    app: {{ include "log-message-processor.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
