name: User Api Docker Image CI

on:
  push:
    paths:
      - users-api/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build and Test with Maven
      run: |
        cd users-api
        mvn clean test
    - name: Build the Docker image
      run: |
        cd users-api
        docker build . --file Dockerfile --tag sgutierrez11/users-api:${{ github.run_number }}
    - name: Log In to Dockerhub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push images to Dockerhub
      run: |
        docker push sgutierrez11/users-api:${{ github.run_number }}
    - name: Activate cd
      run: |
          curl -X POST "${{ secrets.JENKINS_IP }}/generic-webhook-trigger/invoke?token=todo&service=users-apii&tag=${{ github.run_number }}"
